name = "bingo-board-backend"
main = "src/index.js"
compatibility_date = "2026-06-14"

kv_namespaces = [
  { binding = "BINGO_KV", id = "20799c85debc443fbc7b37d527933a95" }
]

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 10
  period = 60
